module.exports = {
  POSTS_RECEIVED: "POSTS_RECEIVED",
  POST_RECEIVED: "POST_RECEIVED",
  COMMENT_RECEIVED: "COMMENT_RECEIVED",
  COMMENT_REMOVED: "COMMENT_REMOVED",
  USERS_RECEIVED: "USERS_RECEIVED",
  RELATIONSHIP_RECEIVED: "RELATIONSHIP_RECEIVED",
  RELATIONSHIP_REMOVED: "RELATIONSHIP_REMOVED"
};
